#!/usr/bin/env python
import os

from setuptools import setup, find_packages

this_directory = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(this_directory, "README.md")) as file:
    long_description = file.read()

setup(
    name="sequencelearn",
    version="0.0.1",
    author="Johannes Hötter",
    author_email="johannes.hoetter@onetask.ai",
    description="Scikit-Learn like Named Entity Recognition modules",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/onetask-ai/sequencelearn",
    keywords=["onetask", "machine learning", "supervised learning", "python"],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
    ],
    package_dir={"": "."},
    packages=find_packages("."),
    install_requires=[
        "absl-py==1.0.0",
        "astunparse==1.6.3",
        "black==21.12b0",
        "cachetools==4.2.4",
        "certifi==2021.10.8",
        "charset-normalizer==2.0.10",
        "click==8.0.3",
        "flatbuffers==2.0",
        "gast==0.4.0",
        "google-auth==2.3.3",
        "google-auth-oauthlib==0.4.6",
        "google-pasta==0.2.0",
        "grpcio==1.43.0",
        "h5py==3.6.0",
        "idna==3.3",
        "importlib-metadata==4.10.0",
        "keras==2.7.0",
        "Keras-Preprocessing==1.1.2",
        "libclang==12.0.0",
        "Markdown==3.3.6",
        "mypy-extensions==0.4.3",
        "numpy==1.21.5",
        "oauthlib==3.1.1",
        "opt-einsum==3.3.0",
        "pathspec==0.9.0",
        "platformdirs==2.4.1",
        "protobuf==3.19.3",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.8",
        "requests==2.27.1",
        "requests-oauthlib==1.3.0",
        "rsa==4.8",
        "six==1.16.0",
        "tensorboard==2.7.0",
        "tensorboard-data-server==0.6.1",
        "tensorboard-plugin-wit==1.8.1",
        "tensorflow-estimator==2.7.0",
        "tensorflow-gpu==2.7.0",
        "tensorflow-io-gcs-filesystem==0.23.1",
        "termcolor==1.1.0",
        "tomli==1.2.3",
        "typing-extensions==4.0.1",
        "urllib3==1.26.8",
        "Werkzeug==2.0.2",
        "wrapt==1.13.3",
        "zipp==3.7.0",
    ],
)
